name: Main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/dependabot.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/dependabot.yml"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming isort[colors]

      - name: Run linting
        run: |
          flake8 . --statistics
          isort . -c --diff
